// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: feedByUrl.sql

package database

import (
	"context"
)

const feedByUrl = `-- name: FeedByUrl :one
SELECT id, created_at, updated_at, name, url, user_id FROM feeds
WHERE url=$1
`

func (q *Queries) FeedByUrl(ctx context.Context, url string) (Feed, error) {
	row := q.db.QueryRowContext(ctx, feedByUrl, url)
	var i Feed
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Url,
		&i.UserID,
	)
	return i, err
}
